version: "3"
services:
  poll:
    build: ./poll
    image: poll
    ports:
      - 5000:80
    depends_on:
      - redis
  result:
    build: ./result
    image: result
    ports:
      - 5001:4242
    depends_on:
      - db
  worker:
    build: ./worker
    image: worker
    depends_on:
      - redis
      - db
  redis:
    image: redis:alpine
  db:
    image: postgres:9.4
networks:
