version: "3"
services:
  poll:
    build: ./poll
    restart: always
    networks:
      - poll-tier
    ports:
      - 5000:80
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    networks:
      - poll-tier

networks:
  poll-tier:
