version: "3"
services:
  poll:
    build: ./poll
    restart: always
    networks:
      - poll-tier
    ports:
      - 5000:80
    depends_on:
      - redis

  result:
    build: ./result
    restart: always
    networks:
      - result-tier
    ports:
      - 5001:4242
    depends_on:
      - db

  worker:
    build: ./worker
    restart: always
    networks:
      - back-tier
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    networks:
      - poll-tier
      - back-tier

  db:
    image: postgres:9.4
    ports:
      - 5432:5432
    volumes:
      - /var/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=schema.sql
    restart: always
    networks:
      - result-tier
      - back-tier

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: